name: AWS Account Creation Request
description: Issue template to request a new AWS Account
title: "[TEAM] - [ACCOUNT NAME]"
labels: aws-account-request
assignees: mouismail
body:
- type: dropdown
  id: unit
  validations:
    required: true
  attributes:
    label: Business Unit
    description: What is your business unit?
    options:
      - Sales
      - Engineering
      - Service Delievery
  render: markdown
- type: input
  id: service_name
  attributes:
    label: Service Name
    description: Service Name
  validations:
    required: true
  render: markdown
- type: dropdown
  id: environment
  validations:
    required: true
  attributes:
    label: Account Environment
    description: What is AWS account environment purpose?
    options:
      - Development
      - Staging
      - Production
  render: markdown
- type: input
  id: cost_center
  attributes:
    label: Cost Center
    description: Your cost center
  validations:
    required: true
  render: markdown
- type: input
  id: spend_limit
  attributes:
    label: Spend limit
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
