name: |
  Repository Creation: Fulfill
description: |
  Action used to fulfill issue-ops requests around creating GitHub repositories.
inputs:
  authentication:
    description: Method to authenticate client; either 'app' or 'token'
    required: true
  application-id:
    description: Application ID of GitHub App, used if `authentication` is 'app'
    required: false
  application-private-key:
    description: Private SSH key of GitHub App, used if `authentication` is 'app'
    required: false
  github-token:
    description: GitHub token, used if `authentication` is 'token'
    required: false
  team-assign:
    description: GitHub team slug for assigning issue
    required: true
  config-repo-owner:
    description: The AWS Configuration Repo owner org
    required: true
  config-repo-name:
    description: The AWS Configuration Repo name
    required: true
  commit-message:
    description: Commit message for updating the config file
    required: true
  content:
    description: The config file update content
    required: true
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate
      id: authenticate
      uses: ./actions/authenticate
      with:
        authentication: ${{ inputs.authentication }}
        application-id: ${{ inputs.application-id }}
        application-private-key: ${{ inputs.application-private-key }}
        github-token: ${{ inputs.github-token }}

    - name: Authorize
      id: authorize
      uses: ./actions/authorize
      with:
        authentication: token
        github-token: ${{ steps.authenticate.outputs.token }}
        team-assign: ${{ inputs.team-assign }}

   - name: Checkout Remote Repo
     id: checkout
     uses: actions/checkout@v4
     with:
        repository:  ${{ inputs.config-repo-owner }}/${{ inputs.config-repo }}
        token: ${{ steps.authenticate.outputs.token }}
        ref: "main"
        path: "config-repo"

  - name: Update Config File
    id: update
    uses: actions/github-script@v6
    with:
        github-token: ${{ steps.authenticate.outputs.token }}
        script: |
          return github.rest.repos.createOrUpdateFileContents({
                ${{ inputs.config-repo-owner }},
                ${{ inputs.config-repo }},
                "config-repo",
                ${{ inputs.commit-message }},
                ${{ inputs.content }},
                committer.name,
                committer.email,
                author.name,
                author.email,
          })
