name: |
  Repository Creation: Finalize
description: |
  Action used to fulfill issue-ops requests around creating GitHub repositories.
inputs:
  authentication:
    description: Method to authenticate client; either 'app' or 'token'
    required: true
  application-id:
    description: Application ID of GitHub App, used if `authentication` is 'app'
    required: false
  application-private-key:
    description: Private SSH key of GitHub App, used if `authentication` is 'app'
    required: false
  github-token:
    description: GitHub token, used if `authentication` is 'token'
    required: false
  config-repo-owner:
    description: The org where is the config repo exsits
    required: true
  config-repo:
    description: The the config repo name
    required: true
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate
      id: authenticate
      uses: ./actions/authenticate
      with:
        authentication: ${{ inputs.authentication }}
        application-id: ${{ inputs.application-id }}
        application-private-key: ${{ inputs.application-private-key }}
        github-token: ${{ inputs.github-token }}

    - name: Checkout Remote Repo
      id: checkout
      uses: actions/checkout@v4
      with:
        repository:  ${{ inputs.config-repo-owner }}/${{ inputs.config-repo }}
        token: ${{ steps.authenticate.outputs.token }}
        ref: "main"
        path: "config-repo"
    - name: Parse issue
      id: parse
      uses: ./actions/parse

    - name: Verify issue form results
      id: inputs
      uses: actions/github-script@v6
      env:
        ISSUE_FORM_JSON: ${{ steps.parse.outputs.data }}
        FINALIZE_FILE: ${{ github.action_path }}/finalize.js
      with:
        github-token: ${{ steps.authenticate.outputs.token }}
        script: |
          const validate = require(process.env.FINALIZE_FILE)
          await validate({github, context, core})
    # - name: Convert Content ot Base64
    #   id: convert
    #   shell: bash
    #   run: |
    #     echo "content=echo '${{ inputs.content }}' | base64" >> "$GITHUB_OUTPUT"
    # - name: Update Config File
    #   id: update
    #   uses: actions/github-script@v6
    #   with:
    #       github-token: ${{ steps.authenticate.outputs.token }}
    #       script: |
    #         return github.rest.repos.createOrUpdateFileContents({
    #               ${{ inputs.config-repo-owner }},
    #               ${{ inputs.config-repo }},
    #               "config-repo",
    #               ${{ inputs.commit-message }},
    #               ${{ steps.convert.outputs.content }},
    #               ${{ inputs.committer-name }},
    #               ${{ inputs.committer-email }},
    #               ${{ inputs.committer-name }},
    #               ${{ inputs.committer-email }},
    #         })
    - name: Verify update repository results
      uses: actions/github-script@v6
      env:
        ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
        CREATE_REPO_JSON: ${{ steps.update.outputs.result }}
      with:
        script: |
          const response = JSON.parse(process.env.CREATE_REPO_JSON)
          const jsonPretty = JSON.stringify(response, null, 2)
          let message;

          if (response.status == 201) {
            message = `@${process.env.ISSUE_AUTHOR} : Your repository has been created: ${response.data.html_url}`
          } else {
            message = `@${context.actor} : Workflow is either not authorized to create repository or something went wrong.`
            core.setFailed(message)
          }

          const body = `
          **${message}**

          <details>
            <summary>Create Organization Repository Response</summary>

            \`\`\`json
            ${jsonPretty}
            \`\`\`
          </details>
          `

          github.rest.issues.createComment({
            ...context.repo,
            issue_number: context.issue.number,
            body
          })

    - name: Close issue
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.update({
            ...context.repo,
            issue_number: context.issue.number,
            state: "closed",
          })
