name: Create Repo - Assign
on:
  issues:
    types:
      - opened
env:
  LGTM_TEAM: aws-account-approval-team
jobs:
  assign:
    name: Assign new issue
    runs-on: ubuntu-20.04
    if: contains(github.event.issue.labels.*.name, 'createrepo') && github.event.action == 'opened'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            sparse-checkout: |
              .github/actions
            path: actions

      - name: Assign
        uses: ./actions/.github/actions/assign
        with:
          authentication: app
          application-id: ${{ secrets.APP_ID }}
          application-private-key: ${{ secrets.APP_PEM }}
          team-assign: ${{ env.LGTM_TEAM }}
  validate:
    name: Validate issue
    runs-on: ubuntu-20.04
    needs: assign
    if: contains(github.event.issue.labels.*.name, 'createrepo') && github.event.issue.state == 'open'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Validate
      uses: ./actions/.github/actions/validate
      with:
        authentication: app
        application-id: ${{ secrets.APP_ID }}
        application-private-key: ${{ secrets.APP_PEM }}
        team-assign: ${{ env.LGTM_TEAM }}
  fulfill:
    name: Fulfill issue
    runs-on: ubuntu-20.04
    needs: validate
    environment:
        name: Production
    if: contains(github.event.issue.labels.*.name, 'createrepo') && github.event.issue.state == 'open'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Fulfill
      uses: ./actions/.github/actions/fulfill
      with:
        authentication: app
        application-id: ${{ secrets.APP_ID }}
        application-private-key: ${{ secrets.APP_PEM }}
        team-assign: ${{ env.LGTM_TEAM }}
