name: AWS Account Creation Validation

on:
  issues:
    types:
      - opened
  workflow_dispatch:

env:
  NEW_REQUEST_LABEL_NAME: "aws-account-request"
  APPROVAL_REQUEST_LABEL_NAME: "aws-account-approval"
  APPROVAL_TEAM: "mo-octocat/aws-account-approval-team"
jobs:
  mention_for_approval:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Validate label and mention for approval
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Check if the issue has the specified label
        LABEL_CHECK=$(jq -r ".issue.labels[] | select(.name == \"$NEW_REQUEST_LABEL_NAME\")" "$GITHUB_EVENT_PATH")

        if [ -n "$LABEL_CHECK" ]; then
          COMMENT_BODY="Hey @$APPROVAL_TEAM, please review and approve this request \"$NEW_REQUEST_LABEL_NAME\"."
          ISSUE_NUMBER=$(jq -r '.issue.number' "$GITHUB_EVENT_PATH")
          gh issue comment "$ISSUE_NUMBER" -R "$GITHUB_REPOSITORY" -b "$COMMENT_BODY"
          gh issue edit "$ISSUE_NUMBER" -R "$GITHUB_REPOSITORY" --remove-label "$NEW_REQUEST_LABEL_NAME" --add-label "$APPROVAL_REQUEST_LABEL_NAME"
        fi
      shell: bash
