name: Create Repo from Template

on:
  workflow_dispatch:
    inputs:
      repo_name:
        required: true

env:
  TEMPLATE_REPO: mo-octocat/flutter-template
  REPO_NAME: aws-123456789
  ORG: mo-octocat

jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: mo-octocat/flutter-template
          event-type: create-repo
          client-payload: '{"repo_name": "${{ github.event.issue.title }}", "description": "${{ github.event.issue.body }}"}'
