name: Create Repo from Template

on:
  workflow_dispatch:

env:
  TEMPLATE_REPO: mo-octocat/flutter-template
  REPO_NAME: aws-123456789
  ORG: mo-octocat

jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Create Repository from Template
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          TEMPLATE_REPO: mo-octocat/flutter-template
          REPO_NAME: aws-123456789
          ORG: mo-octocat
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$TEMPLATE_REPO/generate \
            -f owner=$ORG \
           -f name=$REPO_NAME \
           -f description='This is your first repository' \
           -F include_all_branches=false \
           -F private=false
